/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println("Starting Qcalc.."); 
        
        // StandardCalculator calc = new StandardCalculator();
        // calc.add(1, 3);
        // calc.printResult();

        LogicCalculator calc = new LogicCalculator();
        calc.OR(8, 6);
        calc.printResult();


        // StandardCalculator calc = new StandardCalculator();
        // // calc.multiply(Double.MAX_VALUE, Double.MAX_VALUE);
        // calc.printResult();
    // System.out.println(calc.getResult());
        // System.out.println(new App().getGreeting());
    }
}
